### ISSUE TITLE
Proposed model code

### ISSUE THREAD

**Issue by loretoparisi** [jerrygood0703/KaraSinger#1]
Any plan to publish the proposed model code?
Thanks!

**Comment by jerrygood0703** [comment]
Thank you for your interest! Sadly for now we don't have a plan to release the code.
But feel free to ask any questions about the details of the model.

**Comment by loretoparisi** [comment]
@jerrygood0703 thank you, just wondering a way to try it with different inputs right now, like in the OpenAI [Jukebox](https://openai.com/blog/jukebox/) demo, thanks!

**Comment by jerrygood0703** [comment]
In that case, we're discussing to release a demo webpage where users can input their own lyrics. I will keep you posted if it's available!

**Comment by loretoparisi** [comment]
okay, it sounds cool.
